# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Display
CONFIG_ZMK_DISPLAY=y

# Pointing
CONFIG_ZMK_POINTING=y

# Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# ZMK Studio
CONFIG_ZMK_STUDIO=y

# Battery reporting for split keyboard
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# BLE stability
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE_EXPERIMENTAL_SEC=y
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Connection intervals
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0

# Queues
CONFIG_ZMK_BLE_THREAD_STACK_SIZE=768
CONFIG_ZMK_BLE_KEYBOARD_REPORT_QUEUE_SIZE=36
CONFIG_ZMK_SPLIT_BLE_CENTRAL_POSITION_QUEUE_SIZE=10
CONFIG_ZMK_KSCAN_EVENT_QUEUE_SIZE=12

# Debounce
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=10
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# Sleep
CONFIG_ZMK_IDLE_TIMEOUT=180000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
